spring.datasource.url=${JDBC_DATABASE_URL:${DATABASE_URL}}
spring.datasource.username=${JDBC_DATABASE_USERNAME:studentuser}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:studentpass}

server.port=${PORT:8080}

# Use existing table as-is; don't alter
spring.jpa.hibernate.ddl-auto=none

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=none
